theme: jekyll-theme-slate
title: [KETCube]
description: [Universal Prototyping and Educational IoT Platform]
show_downloads: true
github:
  zip_url: https://github.com/SmartCAMPUSZCU/KETCube-fw/archive/v0.1.1.zip
  zip_url: https://github.com/SmartCAMPUSZCU/KETCube-mainBoard/archive/v0.1.0.zip
